// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: feedFollowers.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createFeedFollowers = `-- name: CreateFeedFollowers :one
INSERT INTO feed_followers(id, created_at, updated_at, user_id, feed_id)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, created_at, updated_at, user_id, feed_id
`

type CreateFeedFollowersParams struct {
	ID        uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
	UserID    uuid.UUID
	FeedID    uuid.UUID
}

func (q *Queries) CreateFeedFollowers(ctx context.Context, arg CreateFeedFollowersParams) (FeedFollower, error) {
	row := q.db.QueryRowContext(ctx, createFeedFollowers,
		arg.ID,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.UserID,
		arg.FeedID,
	)
	var i FeedFollower
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserID,
		&i.FeedID,
	)
	return i, err
}

const getFeedsFollowedByUser = `-- name: GetFeedsFollowedByUser :many
SELECT id, created_at, updated_at, user_id, feed_id FROM feed_followers WHERE user_id = $1
`

func (q *Queries) GetFeedsFollowedByUser(ctx context.Context, userID uuid.UUID) ([]FeedFollower, error) {
	rows, err := q.db.QueryContext(ctx, getFeedsFollowedByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FeedFollower
	for rows.Next() {
		var i FeedFollower
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.UserID,
			&i.FeedID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getFollowersForFeed = `-- name: GetFollowersForFeed :many
SELECT id, created_at, updated_at, user_id, feed_id FROM feed_followers WHERE feed_id = $1
`

func (q *Queries) GetFollowersForFeed(ctx context.Context, feedID uuid.UUID) ([]FeedFollower, error) {
	rows, err := q.db.QueryContext(ctx, getFollowersForFeed, feedID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FeedFollower
	for rows.Next() {
		var i FeedFollower
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.UserID,
			&i.FeedID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
